name: Update Project Work Estimations

on:
  schedule:
    - cron: '*/20 * * * *' # Every 20 minutes
  workflow_dispatch:

jobs:
  update_estimates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4        

      - name: Install dependencies
        run: npm install axios

      - name: Run update script
        env:
          TOKEN_PROJECT_ACCESS_RW: ${{ secrets.TOKEN_PROJECT_ACCESS_RW }}
          GH_ORG_NAME: ${{ vars.ORG_NAME }}
          GH_PROJECT_ID: ${{ vars.PROJECT_ID_ENGINEERINGV2 }}
        run: node .github/scripts/update-project-item-estimation.js
